/**
 * Clinical Clarity — design tokens extracted verbatim from the prototype's
 * Material 3 Tailwind config (codefile.md). Do not restyle.
 */
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.tsx", "./src/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#002045",
        "on-primary": "#ffffff",
        "primary-container": "#1a365d",
        "on-primary-container": "#86a0cd",
        "primary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#adc7f7",
        "on-primary-fixed": "#001b3c",
        "on-primary-fixed-variant": "#2d476f",
        "inverse-primary": "#adc7f7",
        secondary: "#006a68",
        "on-secondary": "#ffffff",
        "secondary-container": "#91f0ed",
        "on-secondary-container": "#006e6d",
        "secondary-fixed": "#94f2f0",
        "secondary-fixed-dim": "#77d6d3",
        "on-secondary-fixed": "#00201f",
        "on-secondary-fixed-variant": "#00504e",
        tertiary: "#1b2127",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#30363c",
        "on-tertiary-container": "#989fa6",
        "tertiary-fixed": "#dde3eb",
        "tertiary-fixed-dim": "#c1c7cf",
        "on-tertiary-fixed": "#161c22",
        "on-tertiary-fixed-variant": "#41474e",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f8f9ff",
        "on-background": "#0d1c2e",
        surface: "#f8f9ff",
        "on-surface": "#0d1c2e",
        "surface-variant": "#d4e4fc",
        "on-surface-variant": "#43474e",
        "surface-dim": "#ccdbf4",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d4e4fc",
        "inverse-surface": "#223144",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#455f88",
        outline: "#74777f",
        "outline-variant": "#c4c6cf",
        /* Dopamine accents — brand-logo family (cyan / aqua / indigo blues) */
        accent: "#0b8fc9",
        "on-accent": "#ffffff",
        "accent-bright": "#35c2f0",
        "accent-container": "#d6f1fb",
        "on-accent-container": "#00455e",
        success: "#1b873f",
        "success-container": "#dcf5e3",
        "on-success-container": "#0b5226",
        "tint-sky": "#def1fc",
        "tint-aqua": "#d8f5f7",
        "tint-mint": "#def5ec",
        "tint-indigo": "#e4e8fb",
        "tint-ice": "#eaf6ff",
      },
      borderRadius: {
        DEFAULT: "4px",
        lg: "8px",
        xl: "12px",
        "2xl": "16px",
        "3xl": "24px",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        gutter: "16px",
      },
      fontFamily: {
        inter: ["Inter_400Regular"],
        "inter-medium": ["Inter_500Medium"],
        "inter-semibold": ["Inter_600SemiBold"],
        "inter-bold": ["Inter_700Bold"],
        "inter-extrabold": ["Inter_800ExtraBold"],
      },
      fontSize: {
        "label-bold": ["14px", { lineHeight: "16px", letterSpacing: "0.01em" }],
        "price-display": ["24px", { lineHeight: "24px" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em" }],
        "medical-term": ["12px", { lineHeight: "16px", letterSpacing: "0.05em" }],
        "headline-md": ["20px", { lineHeight: "28px" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em" }],
        "body-sm": ["14px", { lineHeight: "20px" }],
        "body-lg": ["16px", { lineHeight: "24px" }],
      },
    },
  },
  plugins: [],
};
