export const SPECIALIZATIONS = [
  "Cardiology",
  "Dermatology",
  "Neurology",
  "Orthopedics",
  "Psychiatry",
  "Pediatrics",
  "General Medicine",
  "ENT",
  "Gynecology",
  "Ophthalmology",
  "Endocrinology",
  "Pulmonology",
  "Gastroenterology",
  "Urology",
  "Oncology",
  "Nephrology",
  "Rheumatology",
  "Dentistry",
] as const;
