import { Reminder } from "./types";

export const mockReminders: Reminder[] = [
  {
    id: "rem1",
    title: "Vitamin D3 Sachet",
    subtitle: "60,000 IU · with breakfast",
    type: "medication",
    time: "08:00 AM",
    dateLabel: "Today",
    status: "overdue",
    recurring: "Weekly",
    fromPrescriptionId: "rx1",
  },
  {
    id: "rem2",
    title: "Dermatology Appointment",
    subtitle: "Lilavati Hospital, Bandra",
    type: "appointment",
    time: "11:30 AM",
    dateLabel: "Today",
    status: "upcoming",
  },
  {
    id: "rem3",
    title: "Hydration Goal: 500ml",
    subtitle: "Daily goal",
    type: "hydration",
    time: "02:00 PM",
    dateLabel: "Today",
    status: "upcoming",
    recurring: "Daily",
  },
  {
    id: "rem4",
    title: "Blood Glucose Test",
    subtitle: "Pre-dinner reading",
    type: "test",
    time: "06:00 PM",
    dateLabel: "Today",
    status: "upcoming",
    recurring: "Daily",
  },
  {
    id: "rem5",
    title: "Metformin",
    subtitle: "500 mg · with dinner",
    type: "medication",
    time: "08:00 PM",
    dateLabel: "Today",
    status: "upcoming",
    recurring: "Daily",
    fromPrescriptionId: "rx1",
  },
];
