import {
  Booking,
  DayOption,
  DiagnosticTest,
  HealthPackage,
  Lab,
  TestCategory,
  TimeSlot,
} from "./types";

/** ---------- Test catalogue (₹ pricing, MRP for discount badges) ---------- */
export const mockCategories: TestCategory[] = [
  { id: "heart", kind: "organ", name: "Heart Health", icon: "favorite", testCount: 24 },
  { id: "liver", kind: "organ", name: "Liver Function", icon: "gastroenterology", testCount: 18 },
  { id: "kidney", kind: "organ", name: "Kidney Profile", icon: "water_drop", testCount: 14 },
  { id: "thyroid", kind: "organ", name: "Thyroid", icon: "genetics", testCount: 9 },
  { id: "fatigue", kind: "symptom", name: "Fatigue & Weakness", icon: "battery_low", testCount: 12 },
  { id: "hairloss", kind: "symptom", name: "Hair Loss", icon: "face", testCount: 8 },
  { id: "fever", kind: "symptom", name: "Fever Panel (incl. Dengue, Typhoid)", icon: "thermostat", testCount: 11 },
  { id: "diabetes", kind: "lifestyle", name: "Diabetes Care", icon: "monitor_heart", testCount: 16 },
  { id: "fitness", kind: "lifestyle", name: "Fitness & Sports", icon: "exercise", testCount: 10 },
  { id: "smoking", kind: "lifestyle", name: "Smoker's Panel", icon: "smoke_free", testCount: 7 },
  { id: "womens", kind: "gender", name: "Women's Health", icon: "female", testCount: 22 },
  { id: "mens", kind: "gender", name: "Men's Health", icon: "male", testCount: 17 },
  { id: "xray", kind: "imaging", name: "X-Ray", icon: "skeleton", testCount: 15 },
  { id: "mri", kind: "imaging", name: "MRI Scan", icon: "neurology", testCount: 12 },
  { id: "ultrasound", kind: "imaging", name: "Ultrasound", icon: "waves", testCount: 9 },
  { id: "allergy", kind: "special", name: "Allergy Panels", icon: "allergies", testCount: 13 },
  { id: "genetic", kind: "special", name: "Genetic Screening", icon: "genetics", testCount: 6 },
];

export const mockTests: DiagnosticTest[] = [
  {
    id: "hba1c",
    name: "Blood Sugar (HbA1c) Test",
    shortName: "HbA1c",
    description: "Measures average blood sugar levels over the past 3 months.",
    price: 399,
    mrp: 599,
    homeCollectionFee: 99,
    fastingHours: 10,
    reportEtaHours: 24,
    categoryIds: ["diabetes", "heart"],
    popular: true,
    parameters: 1,
  },
  {
    id: "lipid",
    name: "Lipid Profile",
    shortName: "Lipid",
    description: "Cholesterol, triglycerides and lipoprotein levels for cardiac risk.",
    price: 599,
    mrp: 999,
    homeCollectionFee: 99,
    fastingHours: 12,
    reportEtaHours: 24,
    categoryIds: ["heart", "diabetes"],
    popular: true,
    parameters: 8,
  },
  {
    id: "cbc",
    name: "Complete Blood Count (CBC)",
    shortName: "CBC",
    description: "Red cells, white cells, haemoglobin and platelets overview.",
    price: 299,
    mrp: 449,
    homeCollectionFee: 99,
    reportEtaHours: 12,
    categoryIds: ["fatigue", "fever"],
    popular: true,
    parameters: 21,
  },
  {
    id: "vitd",
    name: "Vitamin D (25-OH)",
    shortName: "Vitamin D",
    description: "Checks vitamin D sufficiency for bone and immune health.",
    price: 899,
    mrp: 1499,
    homeCollectionFee: 99,
    reportEtaHours: 36,
    categoryIds: ["fatigue", "fitness"],
    parameters: 1,
  },
  {
    id: "tsh",
    name: "Thyroid Profile (TSH, T3, T4)",
    shortName: "Thyroid",
    description: "Thyroid stimulating hormone with free T3/T4 levels.",
    price: 499,
    mrp: 799,
    homeCollectionFee: 99,
    reportEtaHours: 24,
    categoryIds: ["thyroid", "fatigue", "hairloss"],
    parameters: 3,
  },
  {
    id: "lft",
    name: "Liver Function Test (LFT)",
    shortName: "LFT",
    description: "Enzymes, bilirubin and proteins reflecting liver health.",
    price: 549,
    mrp: 849,
    homeCollectionFee: 99,
    fastingHours: 8,
    reportEtaHours: 24,
    categoryIds: ["liver", "smoking"],
    parameters: 11,
  },
  {
    id: "holter",
    name: "Holter Monitoring 24-Hour ECG",
    shortName: "Holter ECG",
    description: "24-hour ECG monitoring for heart rhythm analysis. Detects irregular heartbeats, arrhythmias, and silent cardiac events.",
    price: 2499,
    mrp: 3999,
    homeCollectionFee: 0,
    reportEtaHours: 48,
    categoryIds: ["heart"],
    popular: true,
    parameters: 1,
  },
];

export const mockPackages: HealthPackage[] = [
  {
    id: "pkg-comprehensive",
    name: "Full Body Checkup (Comprehensive)",
    description:
      "Complete wellness panel covering cardiac, metabolic, liver, kidney, thyroid and vitamin profiles.",
    price: 1499,
    originalPrice: 2999,
    testIds: ["hba1c", "lipid", "cbc", "vitd", "tsh", "lft"],
    testCount: 68,
    recommendedFor: "Adults 30+ · Annual checkup",
  },
  {
    id: "pkg-cardiac",
    name: "Advanced Cardiac Care",
    description: "Deep cardiac risk panel with lipid, hs-CRP and ECG add-on.",
    price: 999,
    originalPrice: 1799,
    testIds: ["lipid", "cbc"],
    testCount: 32,
    recommendedFor: "Family history of heart disease",
  },
];

export const mockLabs: Lab[] = [
  {
    id: "lab1",
    name: "Aarogya Diagnostics",
    rating: 4.8,
    reviews: 2140,
    distanceKm: 1.2,
    accreditation: "NABL Accredited · ICMR Approved",
    nextAvailable: "Today, 4:00 PM",
  },
  {
    id: "lab2",
    name: "Metro Path Labs",
    rating: 4.6,
    reviews: 1260,
    distanceKm: 2.8,
    accreditation: "NABL / CAP Accredited",
    nextAvailable: "Tomorrow, 7:00 AM",
  },
  {
    id: "lab3",
    name: "Niramaya Wellness Labs",
    rating: 4.9,
    reviews: 3105,
    distanceKm: 4.1,
    accreditation: "NABL Accredited",
    nextAvailable: "Tomorrow, 8:00 AM",
  },
];

export const mockDays: DayOption[] = [
  { id: "d1", dow: "SAT", day: 22, month: "OCT", slotsAvailable: 6 },
  { id: "d2", dow: "SUN", day: 23, month: "OCT", slotsAvailable: 4 },
  { id: "d3", dow: "MON", day: 24, month: "OCT", slotsAvailable: 9 },
  { id: "d4", dow: "TUE", day: 25, month: "OCT", slotsAvailable: 7 },
  { id: "d5", dow: "WED", day: 26, month: "OCT", slotsAvailable: 0 },
  { id: "d6", dow: "THU", day: 27, month: "OCT", slotsAvailable: 8 },
];

export const mockSlots: TimeSlot[] = [
  { id: "s1", time: "06:30 – 07:30 AM", period: "Morning", available: true },
  { id: "s2", time: "07:30 – 08:30 AM", period: "Morning", available: true },
  { id: "s3", time: "10:00 – 11:00 AM", period: "Morning", available: true },
  { id: "s4", time: "12:00 – 01:00 PM", period: "Afternoon", available: false },
  { id: "s5", time: "02:00 – 03:00 PM", period: "Afternoon", available: true },
  { id: "s6", time: "05:00 – 06:00 PM", period: "Evening", available: true },
  { id: "s7", time: "06:00 – 07:00 PM", period: "Evening", available: false },
];

export const mockBookings: Booking[] = [
  {
    id: "bk1",
    testId: "hba1c",
    testName: "Blood Sugar (HbA1c) Test",
    status: "collector_assigned",
    method: "home",
    labName: "Aarogya Diagnostics",
    date: "Fri, Oct 25",
    time: "10:00 – 11:00 AM",
    amount: 498,
    fastingHours: 10,
    collector: {
      name: "Ramesh Kumar",
      idVerified: true,
      rating: 4.9,
      etaMinutes: 25,
      status: "on_the_way",
    },
  },
  {
    id: "bk2",
    testId: "lipid",
    testName: "Lipid Profile",
    status: "report_ready",
    method: "lab",
    labName: "Niramaya Wellness Labs",
    date: "Mon, Oct 14",
    time: "08:00 AM",
    amount: 599,
    fastingHours: 12,
  },
  {
    id: "bk3",
    testId: "cbc",
    testName: "Complete Blood Count (CBC)",
    status: "delayed",
    method: "home",
    labName: "Metro Path Labs",
    date: "Wed, Oct 16",
    time: "09:00 AM",
    amount: 398,
  },
];

/** ---------- Search ---------- */
export const popularSearches = ["HbA1c", "Thyroid", "Vitamin D", "CBC", "Full Body Checkup"];
